version: "3.3"

services:
  db:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teste_jpa
    restart: always